#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

#cleanCase

rm -rf EnSight Ensight Fieldview > /dev/null 2>&1
# rm -f constant/polyMesh/boundary > /dev/null 2>&1

#find . \( -name core -o -name 'core.[1-9]*' \) -exec rm {} \;
#find . \( -name '*.pvs' -o -name '*.OpenFOAM' \) -exec rm {} \;
#rm -rf logs testLoopReport

foamCleanTutorials

rm -rf *[1-9]*
rm -f log.*

#------------------------------------------------------------------------------
