#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`

touch laplacianDyMFoam.foam
#cp -r ./constant/polyMesh.BAK ./constant/polyMesh
runApplication blockMesh
runApplication $application
#runApplication foamToEnsight
#runApplication foamToEnsightParts
#runApplication foamToVTK

#------------------------------------------------------------------------------
