#!/bin/bash
#
#-------------------------------------------------#
# Contributor: Tobias Holzmann                    #
# Updated on:  10 September 2021                  #
#-------------------------------------------------#
# Topic:       Adaptive mesh refinement           #
# OpenFOAM:    version 9 (Foundation)             #
#-------------------------------------------------#
# Website:     https://Holzmann-cfd.com           #
# Email:       community@Holzmann-cfd.com         #
#-------------------------------------------------#


#------------------------------------------------------------------------------
foamVersion="OpenFOAM-9"


#------------------------------------------------------------------------------
cd ${0%/*} || exit 1
clear
source clean
source .color
source .preamble


#------------------------------------------------------------------------------
echo -e "\n
Start meshing
-------------------------------------------------------------------------------
"


#------------------------------------------------------------------------------
echo -e "   - Create background mesh"
ideasUnvToFoam cad/backgroundMesh.unv > logMeshing


#------------------------------------------------------------------------------
echo -e "   - Create surface feature edges"
surfaceFeatures >> logMeshing


#------------------------------------------------------------------------------
echo -e "   - Meshing with snappyHexMesh"
snappyHexMesh -overwrite >> logMeshing


#------------------------------------------------------------------------------
echo -e "   - Change boundary types of front and back"
changeDictionary >> logMeshing


#------------------------------------------------------------------------------
echo -e "   - Prepare and clean case for adaptive mesh refinement"
rm -rf 0 const*/polyMesh/refine*


#------------------------------------------------------------------------------
echo -e "   - Copy 0.orig to 0"
cp -r 0.orig 0


#------------------------------------------------------------------------------
echo -e "\n
-------------------------------------------------------------------------------
End Meshing\n\n"


#------------------------------------------------------------------------------
echo -e "\n
Start simulation
-------------------------------------------------------------------------------
"


#------------------------------------------------------------------------------
echo -e "   - Call pimpleFoam and start the simulation (~10 - 20 minutes)"
pimpleFoam > logSimulation


#------------------------------------------------------------------------------
echo -e "   - Simulation finished, use 'paraFoam' to check the results"


#------------------------------------------------------------------------------
